---

- hosts: all
  become: true
  tasks:

  - name: install lastest version of mailx
    yum:
      name:
        - mailx
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"
  - name: Stop service httpd, if started
    service:
      name: httpd
      state: started
    when: ansible_distribution == "RedHat"

  - name: install latest version of apache 
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"
